### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by itsmenewbie03** [itsmenewbie03/yawascript#1]
## Roadmap
- [x]  Decide the keyword to map to Brainfuck instructions
## Basic Parser
- [x]  Implement equivalent of `.` `<` `>` `+` `-`
## Advanced Parser
- [x] Implement equivalent of `[` `]` `,`

**Comment by itsmenewbie03** [comment]
This should be considered complete and the issue of working with nested loops is tracked in #2
